/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Account struct {

	// Account id
	Id int64 `json:"id"`

	// First Name
	FirstName string `json:"first_name"`

	// Last Name
	LastName string `json:"last_name"`

	// Account used private quota
	UsedQuotaPrivate int64 `json:"used_quota_private"`

	// Date of last account modification
	ModifiedDate string `json:"modified_date"`

	// Account total used quota
	UsedQuota int64 `json:"used_quota"`

	// Date when account was created
	CreatedDate string `json:"created_date"`

	// Account quota
	Quota int64 `json:"quota"`

	// Account group id
	GroupId int64 `json:"group_id"`

	// Account institution user id
	InstitutionUserId string `json:"institution_user_id"`

	// Account institution
	InstitutionId int64 `json:"institution_id"`

	// User email
	Email string `json:"email"`

	// Account public used quota
	UsedQuotaPublic int64 `json:"used_quota_public"`

	// True if a quota request is pending
	PendingQuotaRequest bool `json:"pending_quota_request"`

	// Account activity status
	Active int64 `json:"active"`

	// Maximum upload size for account
	MaximumFileSize int64 `json:"maximum_file_size"`
}
