/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AccountReport struct {

	// A unique ID for the AccountRecord
	Id int64 `json:"id"`

	// The ID of the account which generated this report.
	AccountId int64 `json:"account_id"`

	// Date when the AccountReport was requested
	CreatedDate string `json:"created_date"`

	// Status of the report
	Status string `json:"status"`

	// The download link for the generated XLSX
	DownloadUrl string `json:"download_url"`

	// The group ID that was used to filter the report, if any.
	GroupId int64 `json:"group_id"`
}
