/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CollectionVersions struct {

	// Version number
	Id int64 `json:"id"`

	// Api endpoint for the collection version
	Url string `json:"url"`
}
