/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CurationDetail struct {

	// The review id
	Id int64 `json:"id"`

	// The group in which the article is present.
	GroupId int64 `json:"group_id"`

	// The ID of the account of the owner of the article of this review.
	AccountId int64 `json:"account_id"`

	// The ID of the account to which this review is assigned.
	AssignedTo int64 `json:"assigned_to"`

	// The ID of the article of this review.
	ArticleId int64 `json:"article_id"`

	// The Version number of the article in review.
	Version int64 `json:"version"`

	// The number of comments in the review.
	CommentsCount int64 `json:"comments_count"`

	// The status of the review.
	Status string `json:"status"`

	// The creation date of the review.
	CreatedDate string `json:"created_date"`

	// The date the review has been modified.
	ModifiedDate string `json:"modified_date"`
}
