/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type GroupEmbargoOptions struct {

	// Embargo option id
	Id int64 `json:"id"`

	// Embargo permission type
	Type_ string `json:"type"`

	// IP range name; value appears if type is ip_range
	IpName string `json:"ip_name"`
}
