/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Group struct {

	// Group id
	Id int64 `json:"id"`

	// Group name
	Name string `json:"name"`

	// Group resource id
	ResourceId string `json:"resource_id"`

	// Parent group if any
	ParentId int64 `json:"parent_id"`

	// HR code associated with group, if code exists
	AssociationCriteria string `json:"association_criteria"`
}
