/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ItemType struct {

	// The ID of the item type.
	Id int64 `json:"id"`

	// The name of the item type
	Name string `json:"name"`

	// The string identifier of the item type.
	StringId string `json:"string_id"`

	// The string identifying the icon of the item type.
	Icon string `json:"icon"`

	// The description of the item type.
	PublicDescription string `json:"public_description"`

	// The selectable status
	IsSelectable bool `json:"is_selectable"`

	// The URL name of the item type.
	UrlName string `json:"url_name"`
}
