/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type License struct {

	// License value
	Value int64 `json:"value"`

	// License name
	Name string `json:"name"`

	// License url
	Url string `json:"url"`
}
