/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PrivateLink struct {

	// Private link id
	Id string `json:"id"`

	// True if private link is active
	IsActive bool `json:"is_active"`

	// Date when link will expire
	ExpiresDate string `json:"expires_date"`

	// HTML url for private link
	HtmlLocation string `json:"html_location"`
}
