/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ProjectNote struct {

	// Project note id
	Id int64 `json:"id"`

	// User who wrote the note
	UserId int64 `json:"user_id"`

	// Note Abstract - short/truncated content
	Abstract string `json:"abstract"`

	// Username of the one who wrote the note
	UserName string `json:"user_name"`

	// Date when note was created
	CreatedDate string `json:"created_date"`

	// Date when note was last modified
	ModifiedDate string `json:"modified_date"`
}
