/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ProjectPrivate struct {

	// Api endpoint
	Url string `json:"url"`

	// Project id
	Id int64 `json:"id"`

	// Project title
	Title string `json:"title"`
}
