/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Role struct {

	// Role id
	Id int64 `json:"id"`

	// Role name
	Name string `json:"name"`

	// Role category
	Category string `json:"category"`

	// Role description
	Description string `json:"description"`
}
