/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ShortCustomField struct {

	// Custom field id
	Id int64 `json:"id"`

	// Custom field name
	Name string `json:"name"`

	// Custom field type
	FieldType string `json:"field_type"`
}
