/* 
 * Figshare API
 *
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ShortAccount struct {

	// Account id
	Id int64 `json:"id"`

	// First Name
	FirstName string `json:"first_name"`

	// Last Name
	LastName string `json:"last_name"`

	// Account institution
	InstitutionId int64 `json:"institution_id"`

	// User email
	Email string `json:"email"`

	// Account activity status
	Active int64 `json:"active"`

	// Account institution user id
	InstitutionUserId string `json:"institution_user_id"`

	// Total storage available to account, in bytes
	Quota int64 `json:"quota"`

	// Storage used by the account, in bytes
	UsedQuota int64 `json:"used_quota"`

	// User id associated with account, useful for example for adding the account as an author to an item
	UserId int64 `json:"user_id"`

	// ORCID iD associated to account
	OrcidId string `json:"orcid_id"`
}
