/*
 * Figshare API
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Author;
import io.swagger.client.model.AuthorComplete;
import io.swagger.client.model.ErrorMessage;
import io.swagger.client.model.PrivateAuthorsSearch;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthorsApi
 */
@Ignore
public class AuthorsApiTest {

    private final AuthorsApi api = new AuthorsApi();

    
    /**
     * Author details
     *
     * View author details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void privateAuthorDetailsTest() throws ApiException {
        Long authorId = null;
        AuthorComplete response = api.privateAuthorDetails(authorId);

        // TODO: test validations
    }
    
    /**
     * Search Authors
     *
     * Search for authors
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void privateAuthorsSearchTest() throws ApiException {
        PrivateAuthorsSearch search = null;
        List<Author> response = api.privateAuthorsSearch(search);

        // TODO: test validations
    }
    
}
