/*
 * Figshare API
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TimelineUpdate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-14T12:44:49.389+03:00")
public class TimelineUpdate {
  @SerializedName("firstOnline")
  private String firstOnline = null;

  @SerializedName("publisherPublication")
  private String publisherPublication = null;

  @SerializedName("publisherAcceptance")
  private String publisherAcceptance = null;

  public TimelineUpdate firstOnline(String firstOnline) {
    this.firstOnline = firstOnline;
    return this;
  }

   /**
   * Online posted date
   * @return firstOnline
  **/
  @ApiModelProperty(example = "2015-12-31", value = "Online posted date")
  public String getFirstOnline() {
    return firstOnline;
  }

  public void setFirstOnline(String firstOnline) {
    this.firstOnline = firstOnline;
  }

  public TimelineUpdate publisherPublication(String publisherPublication) {
    this.publisherPublication = publisherPublication;
    return this;
  }

   /**
   * Publish date
   * @return publisherPublication
  **/
  @ApiModelProperty(example = "2015-12-31", value = "Publish date")
  public String getPublisherPublication() {
    return publisherPublication;
  }

  public void setPublisherPublication(String publisherPublication) {
    this.publisherPublication = publisherPublication;
  }

  public TimelineUpdate publisherAcceptance(String publisherAcceptance) {
    this.publisherAcceptance = publisherAcceptance;
    return this;
  }

   /**
   * Date when the item was accepted for publication
   * @return publisherAcceptance
  **/
  @ApiModelProperty(example = "2015-12-31", value = "Date when the item was accepted for publication")
  public String getPublisherAcceptance() {
    return publisherAcceptance;
  }

  public void setPublisherAcceptance(String publisherAcceptance) {
    this.publisherAcceptance = publisherAcceptance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimelineUpdate timelineUpdate = (TimelineUpdate) o;
    return Objects.equals(this.firstOnline, timelineUpdate.firstOnline) &&
        Objects.equals(this.publisherPublication, timelineUpdate.publisherPublication) &&
        Objects.equals(this.publisherAcceptance, timelineUpdate.publisherAcceptance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstOnline, publisherPublication, publisherAcceptance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimelineUpdate {\n");
    
    sb.append("    firstOnline: ").append(toIndentedString(firstOnline)).append("\n");
    sb.append("    publisherPublication: ").append(toIndentedString(publisherPublication)).append("\n");
    sb.append("    publisherAcceptance: ").append(toIndentedString(publisherAcceptance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

