/*
 * Figshare API
 * Figshare apiv2. Using Swagger 2.0
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * User
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-14T12:44:49.389+03:00")
public class User {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("first_name")
  private String firstName = null;

  @SerializedName("last_name")
  private String lastName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("is_active")
  private Boolean isActive = null;

  @SerializedName("url_name")
  private String urlName = null;

  @SerializedName("is_public")
  private Boolean isPublic = null;

  @SerializedName("job_title")
  private String jobTitle = null;

  @SerializedName("orcid_id")
  private String orcidId = null;

  public User id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * User id
   * @return id
  **/
  @ApiModelProperty(example = "1495682", required = true, value = "User id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public User firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * First Name
   * @return firstName
  **/
  @ApiModelProperty(example = "Doe", required = true, value = "First Name")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public User lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Last Name
   * @return lastName
  **/
  @ApiModelProperty(example = "John", required = true, value = "Last Name")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public User name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Full Name
   * @return name
  **/
  @ApiModelProperty(example = "John Doe", required = true, value = "Full Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public User isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Account activity status
   * @return isActive
  **/
  @ApiModelProperty(example = "true", required = true, value = "Account activity status")
  public Boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public User urlName(String urlName) {
    this.urlName = urlName;
    return this;
  }

   /**
   * Name that appears in website url
   * @return urlName
  **/
  @ApiModelProperty(example = "John_Doe", required = true, value = "Name that appears in website url")
  public String getUrlName() {
    return urlName;
  }

  public void setUrlName(String urlName) {
    this.urlName = urlName;
  }

  public User isPublic(Boolean isPublic) {
    this.isPublic = isPublic;
    return this;
  }

   /**
   * Account public status
   * @return isPublic
  **/
  @ApiModelProperty(example = "true", required = true, value = "Account public status")
  public Boolean getIsPublic() {
    return isPublic;
  }

  public void setIsPublic(Boolean isPublic) {
    this.isPublic = isPublic;
  }

  public User jobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * User Job title
   * @return jobTitle
  **/
  @ApiModelProperty(example = "programmer", required = true, value = "User Job title")
  public String getJobTitle() {
    return jobTitle;
  }

  public void setJobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
  }

  public User orcidId(String orcidId) {
    this.orcidId = orcidId;
    return this;
  }

   /**
   * Orcid associated to this User
   * @return orcidId
  **/
  @ApiModelProperty(example = "1234-5678-9123-1234", required = true, value = "Orcid associated to this User")
  public String getOrcidId() {
    return orcidId;
  }

  public void setOrcidId(String orcidId) {
    this.orcidId = orcidId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.id, user.id) &&
        Objects.equals(this.firstName, user.firstName) &&
        Objects.equals(this.lastName, user.lastName) &&
        Objects.equals(this.name, user.name) &&
        Objects.equals(this.isActive, user.isActive) &&
        Objects.equals(this.urlName, user.urlName) &&
        Objects.equals(this.isPublic, user.isPublic) &&
        Objects.equals(this.jobTitle, user.jobTitle) &&
        Objects.equals(this.orcidId, user.orcidId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, firstName, lastName, name, isActive, urlName, isPublic, jobTitle, orcidId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    urlName: ").append(toIndentedString(urlName)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("    jobTitle: ").append(toIndentedString(jobTitle)).append("\n");
    sb.append("    orcidId: ").append(toIndentedString(orcidId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

